version: '3.8'

services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - task-service
    networks:
      - app-network

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_USER=admin
        - DB_PASSWORD=12345
        - DB_NAME=auth_db
        - JWT_SECRET=my_secret_key
    depends_on:
      - postgres
    networks:
      - app-network

  task-service:
    build:
      context: ../task-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_USER=admin
        - DB_PASSWORD=12345
        - DB_NAME=task_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

