FROM golang:1.22-alpine AS builder
WORKDIR  /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o auth-service ./cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/auth-service .
COPY config/config.yaml ./config/
EXPOSE 8081
CMD ["./auth-service"]
